# Generated by Django 2.1.3 on 2018-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20181120_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
